--CREATE DATABASE ProductsService
--GO
--USE ProductsService
--GO

CREATE TABLE Roles
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	Title NVARCHAR(25) NOT NULL
)

CREATE TABLE [Users]
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	[Login] NVARCHAR(50) NOT NULL,
	[Password] NVARCHAR(50) NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	MiddleName NVARCHAR(50) NOT NULL,
	PhoneNumber NVARCHAR(11) NOT NULL,
	Email NVARCHAR(255) NOT NULL,
	RoleId INT REFERENCES Roles(ID) NOT NULL,
)

CREATE TABLE ProductCategories
(
	ID INT IDENTITY PRIMARY KEY NOT NULL
	Title NVARCHAR(100) NOT NULL,
)

CREATE TABLE Products
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	Title NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	Cost DECIMAL(10,2) NOT NULL,
	CategoryId INT REFERENCES ProductCategories(ID) NOT NULL,
)

CREATE TABLE [Orders]
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	ProductId INT REFERENCES Products(ID) NOT NULL,
	UserId INT REFERENCES Users(ID) NOT NULL,
	OrderStatus NVARCHAR(20) NOT NULL
)

CREATE TABLE [Services]
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	Title NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL
)


CREATE TABLE [Requests]
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	UserId INT REFERENCES Users(ID) NOT NULL,
	ServiceId INT REFERENCES [Services](ID) NOT NULL,
	RequestStatus NVARCHAR(20) NOT NULL
)